    spring.application.name=kanban-api

    # Database
    spring.datasource.url=jdbc:postgresql://localhost:5432/kanban_db
    spring.datasource.username=kanban_user
    spring.datasource.password=kanban_pass
    spring.datasource.driver-class-name=org.postgresql.Driver

    # JPA
    spring.jpa.open-in-view=false
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

    # App
    server.port=8080